name: CI

on:
  pull-request:
  schedule:
  - cron: "0 0 * * *"

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node.js
       uses: actions/setup-node@v2
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run update
      run: node ci/update.mjs
    - uses: EndBug/add-and-commit@v7
