name: CI

on:
  pull_request:
  schedule:
  - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: latest
    - name: Checkout
      uses: actions/checkout@v4
    - name: Run update
      run: node ci/update.mjs
    - uses: EndBug/add-and-commit@v9
